development:
  adapter: postgresql
  encoding: unicode
  database: nozet
  pool: 5
  username: postgres
  password: Abc@123456789
test:
  adapter: postgresql
  encoding: unicode
  database: nozet
  pool: 5
  username: postgres
  password: Abc@123456789
production:
  adapter: postgresql
  encoding: unicode
  database: nozet
  pool: 5
  username: postgres
  password: Abc@123456789